# Generated by Django 3.1 on 2020-08-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship_tempor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tempor',
        ),
    ]
